export const columns: { id: string; label: string }[] = [
  { id: "templateName", label: "Template Name" },
  { id: "channels", label: "Channels" },
  { id: "type", label: "Type" },
  { id: "role", label: "Role" },
  { id: "lastUsed", label: "Last Used" },
  { id: "status", label: "Status" },
  { id: "action", label: "Action" },
];

export const rows = [
  {
    templateName: "Tax Payment Reminder",
    channels: ["App", "SMS"],
    type: "Utility",
    role: ["Citizen"],
    lastUsed: "2024-10-28",
    status: "Active",
  },
  {
    templateName: "Property Verification Notice",
    channels: ["App", "SMS"],
    type: "General",
    role: ["Citizen", "Agent"],
    lastUsed: "2024-10-25",
    status: "Active",
  },
  {
    templateName: "New Property Registration Confirmation",
    channels: ["App", "SMS", "WhatsApp"],
    type: "General",
    role: ["Citizen", "Agent"],
    lastUsed: "2024-10-27",
    status: "Active",
  },
  {
    templateName: "Demand Recalibration Update",
    channels: ["App", "SMS"],
    type: "Utility",
    role: ["Citizen"],
    lastUsed: "2024-10-01",
    status: "Active",
  },
  {
    templateName: "Annual Tax Statement",
    channels: ["App", "SMS", "Email"],
    type: "Utility",
    role: ["Citizen"],
    lastUsed: "2024-09-15",
    status: "Active",
  },
  {
    templateName: "Agent Assignment Notification",
    channels: ["App", "SMS"],
    type: "General",
    role: ["Agent"],
    lastUsed: "2024-09-10",
    status: "Inactive",
  },
  {
    templateName: "Property Transfer Alert",
    channels: ["App", "SMS", "WhatsApp"],
    type: "General",
    role: ["Citizen", "Agent"],
    lastUsed: "2024-08-30",
    status: "Active",
  },
  {
    templateName: "Payment Failure Notice",
    channels: ["App", "SMS"],
    type: "Utility",
    role: ["Citizen"],
    lastUsed: "2024-08-20",
    status: "Active",
  },
  {
    templateName: "Survey Completion Reminder",
    channels: ["App", "SMS"],
    type: "General",
    role: ["Agent"],
    lastUsed: "2024-08-05",
    status: "Inactive",
  },
  {
    templateName: "Document Submission Request",
    channels: ["App", "SMS", "Email"],
    type: "General",
    role: ["Citizen"],
    lastUsed: "2024-07-25",
    status: "Active",
  },
];