# Common Labels
labels:
  app: "mdms-v2"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "mdms-v2"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "mdms_v2_schema"
    image:
      repository: "mdms-v2-db"

# Container Configs
image:
  repository: "mdms-v2"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/mdms-v2/health"
  readinessProbePath: "/mdms-v2/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms512m"
java-args: "-Dspring.profiles.active=monitoring"
egov-mdms-schema-definition-save-topic: "save-mdms-schema-definition"
egov-mdms-data-save-topic: "save-mdms-data"

# Additional Container Envs
env: |
  - name: spring.datasource.url
    value: jdbc:postgresql://10.232.161.103:32431/property-enumeration
  - name: spring.redis.host
    value: 10.232.161.103
  - name: spring.redis.port
    value: '32380'
  - name: spring.redis.cache.expiration.hours
    value: '1'