export const columns: { id: string; label: string }[] = [
  { id: "fileName", label: "File Name" },
  { id: "type", label: "Type" },
  { id: "features", label: "Features" },
  { id: "size", label: "Size" },
  { id: "uploadedBy", label: "Uploaded By" },
  { id: "status", label: "Status" },
  { id: "action", label: "Action" },
];

export const rows = [
  {
    fileName: "BBMP_Zones_2024.shp",
    type: "Zones",
    features: "Property Tax Officer",
    size: "2.4 MB",
    uploadedBy: "Priya Sharma",
    status: "Active",
  },
  {
    fileName: "BBMP_Wards_2024.shp",
    type: "Wards",
    features: "GIS Officer",
    size: "5.8 MB",
    uploadedBy: "Priya Sharma",
    status: "Active",
  },
  {
    fileName: "BBMP_Mohallas_Zone3.shp",
    type: "Mohallas",
    features: "Field Agent",
    size: "1.2 MB",
    uploadedBy: "Priya Sharma",
    status: "Active",
  },
  {
    fileName: "BBMP_Streets_2024.shp",
    type: "Streets",
    features: "Surveyor",
    size: "3.1 MB",
    uploadedBy: "Amit Kumar",
    status: "Inactive",
  },
  {
    fileName: "BBMP_Blocks_2024.shp",
    type: "Blocks",
    features: "Data Analyst",
    size: "4.7 MB",
    uploadedBy: "Sunita Rao",
    status: "Active",
  },
  {
    fileName: "BBMP_Buildings_2024.shp",
    type: "Buildings",
    features: "Building Inspector",
    size: "6.2 MB",
    uploadedBy: "Rahul Singh",
    status: "Pending",
  },
  {
    fileName: "BBMP_Parks_2024.shp",
    type: "Parks",
    features: "Environment Officer",
    size: "2.9 MB",
    uploadedBy: "Meena Joshi",
    status: "Active",
  },
  {
    fileName: "BBMP_Roads_2024.shp",
    type: "Roads",
    features: "Transport Officer",
    size: "5.0 MB",
    uploadedBy: "Vikram Patel",
    status: "Inactive",
  },
  {
    fileName: "BBMP_Lakes_2024.shp",
    type: "Lakes",
    features: "Water Board",
    size: "3.8 MB",
    uploadedBy: "Anjali Menon",
    status: "Active",
  },
  {
    fileName: "BBMP_Schools_2024.shp",
    type: "Schools",
    features: "Education Dept",
    size: "2.5 MB",
    uploadedBy: "Suresh Babu",
    status: "Pending",
  },
];
