/**
 * API slice for managing application inbox-related endpoints for the Service Manager.
 * Provides endpoints to fetch all applications and applications under a specific jurisdiction (zone/ward),
 * with support for pagination and cache management using RTK Query.
 */
import { apiSlice } from '../../../../../store/apiSlice'
import { TAG_TYPES } from '../../../../../store/tagTypes'
import type { 
    GetAllApplicationsResponse, 
    // GetAllApplicationsRequest 
} from '../models/getAllApplicationsModel'

// Extend the base API slice with endpoints related to the application inbox
export const applicationInboxApi = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        // getAllApplicationsInbox: builder.query<GetAllApplicationsResponse, GetAllApplicationsRequest>({
        //     query: ({ page = 0, size = 20 } = {}) => ({
        //         url: `/v1/applications?page=${page}&size=${size}`,
        //         method: 'GET',
        //         headers: {
        //             'X-User-Role': 'SERVICE_MANAGER',
        //         },
        //     }),
        //     providesTags: [TAG_TYPES.APPLICATIONS],
        // }),

        getAllApplicationsUnderJurisdiction: builder.query<
    GetAllApplicationsResponse,
    { zoneNo: string; wardNos: string[]; page?: number; size?: number; status?: string; priority?: string; assignedAgent?: string; applicationNo?: string }
>({
    query: ({ page = 0, size = 20, zoneNo, wardNos, status, priority, assignedAgent, applicationNo }) => {
        const zoneParam = `zoneNo=${encodeURIComponent(zoneNo)}`;
        const wardParams = wardNos.map(w => `wardNo=${encodeURIComponent(w)}`).join('&');
        const statusParam = status ? `status=${encodeURIComponent(status)}` : '';
        const priorityParam = priority ? `priority=${encodeURIComponent(priority)}` : '';
        const agentParam = assignedAgent ? `assignedAgent=${encodeURIComponent(assignedAgent)}` : '';
        const applicationNoParam = applicationNo ? `applicationNo=${encodeURIComponent(applicationNo)}` : '';
        const url = `/v1/applications/search?${zoneParam}&${wardParams}&${statusParam}&status=VERIFIED&${priorityParam}&${agentParam}&${applicationNoParam}&page=${page}&size=${size}`;
        console.log('Built jurisdiction query for applications:', url);
        return {
            url,
            method: 'GET',
            headers: {
                'X-User-Role': 'SERVICE_MANAGER',
            },
        };
    },
    providesTags: [TAG_TYPES.APPLICATIONS],
}),
    }),
})

// Export hooks generated by RTK Query for use in components
export const { 
    // useGetAllApplicationsInboxQuery,
    useGetAllApplicationsUnderJurisdictionQuery 
} = applicationInboxApi;